version: "3"

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
    volumes:
      - ./config:/config
      - ../data:/mnt/media
    networks:
      - media-network
    ports:
      - 8988:8989

networks:
  media-network:
    driver: bridge
    external: true
