version: "3"

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: ombi
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
    volumes:
      - ./config:/config
    networks:
      - media-network
    ports:
      - 3579:3579

networks:
  media-network:
    driver: bridge
    external: true
