version: "3"

services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
      VERSION: docker
      PLEX_CLAIM: claim-XXXXXXXXXXXXXXXXXXXX
    volumes:
      - ./config:/config
      - ../data/tv:/tv
      - ../data/movies:/movies
    networks:
      - media-network
    ports:
      - 32400:32400/tcp

networks:
  media-network:
    driver: bridge
    external: true
