version: "3"

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    environment:
      PLEX_UID: 0
      PLEX_GID: 0
      TZ: Europe/Amsterdam
      VERSION: docker
    volumes:
      - ./config:/config
      - ../data/tv:/tv
      - ../data/movies:/movies
    networks:
      - media-network
    ports:
      - 32400:32400/tcp

networks:
  media-network:
    driver: bridge
    external: true
