version: "3"

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Amsterdam
    volumes:
      - ./config:/config
      - ../data:/mnt/media
    networks:
      - media-network
    ports:
      - 7878:7878

networks:
  media-network:
    driver: bridge
    external: true
