version: "3"

services:
  jackett:
    image: linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
    volumes:
      - ./config:/config
      - ../data/torrents/completed:/downloads
    networks:
      - media-network
    ports:
      - 9117:9117

networks:
  media-network:
    driver: bridge
    external: true
