version: "3"

services:
  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: Europe/Amsterdam
    volumes:
      - ./config:/config
      - ../data/torrents:/downloads
    networks:
      - media-network
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp

networks:
  media-network:
    driver: bridge
    external: true
